services:
  - type: web
    name: word-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        value: postgresql://word_game_user:w1mSBI2N2j0pTuHpU0PmjxLvfzTeLTUT@dpg-d3ftdg3e5dus73euufk0-a/word_game